/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlumnoWebSumV2AsistenciaRouteImport } from './routes/alumnoWebSum.v2.asistencia'
import { Route as AlumnoWebSumV2InicioRouteImport } from './routes/alumnoWebSum.v2.inicio'
import { Route as AlumnoWebSumV2ManualesRouteImport } from './routes/alumnoWebSum.v2.manuales'
import { Route as AlumnoWebSumV2PlanEstudiosRouteImport } from './routes/alumnoWebSum.v2.planEstudios'
import { Route as AlumnoWebSumV2TutoriaRouteImport } from './routes/alumnoWebSum.v2.tutoria'
import { Route as AlumnoWebSumV2InformacionFichaSocioeconomicaRouteImport } from './routes/alumnoWebSum.v2.informacion.fichaSocioeconomica'
import { Route as AlumnoWebSumV2InformacionFormularioDatosRouteImport } from './routes/alumnoWebSum.v2.informacion.formularioDatos'
import { Route as AlumnoWebSumV2InformacionHistorialRouteImport } from './routes/alumnoWebSum.v2.informacion.historial'
import { Route as AlumnoWebSumV2InformacionPerfilRouteImport } from './routes/alumnoWebSum.v2.informacion.perfil'
import { Route as AlumnoWebSumV2MatriculaInformacionRouteImport } from './routes/alumnoWebSum.v2.matricula.informacion'
import { Route as AlumnoWebSumV2MatriculaProgramacionRouteImport } from './routes/alumnoWebSum.v2.matricula.programacion'
import { Route as AlumnoWebSumV2ReportesDeudasRouteImport } from './routes/alumnoWebSum.v2.reportes.deudas'
import { Route as AlumnoWebSumV2ReportesEvaluacionesRouteImport } from './routes/alumnoWebSum.v2.reportes.evaluaciones'
import { Route as AlumnoWebSumV2ReportesHorariosRouteImport } from './routes/alumnoWebSum.v2.reportes.horarios'
import { Route as AlumnoWebSumV2ReportesMatriculaRouteImport } from './routes/alumnoWebSum.v2.reportes.matricula'
import { Route as AlumnoWebSumV2ReportesPrematriculaRouteImport } from './routes/alumnoWebSum.v2.reportes.prematricula'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumnoWebSumV2AsistenciaRoute =
  AlumnoWebSumV2AsistenciaRouteImport.update({
    id: '/alumnoWebSum/v2/asistencia',
    path: '/alumnoWebSum/v2/asistencia',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlumnoWebSumV2InicioRoute = AlumnoWebSumV2InicioRouteImport.update({
  id: '/alumnoWebSum/v2/inicio',
  path: '/alumnoWebSum/v2/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumnoWebSumV2ManualesRoute = AlumnoWebSumV2ManualesRouteImport.update({
  id: '/alumnoWebSum/v2/manuales',
  path: '/alumnoWebSum/v2/manuales',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumnoWebSumV2PlanEstudiosRoute =
  AlumnoWebSumV2PlanEstudiosRouteImport.update({
    id: '/alumnoWebSum/v2/planEstudios',
    path: '/alumnoWebSum/v2/planEstudios',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlumnoWebSumV2TutoriaRoute = AlumnoWebSumV2TutoriaRouteImport.update({
  id: '/alumnoWebSum/v2/tutoria',
  path: '/alumnoWebSum/v2/tutoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumnoWebSumV2InformacionFichaSocioeconomicaRoute =
  AlumnoWebSumV2InformacionFichaSocioeconomicaRouteImport.update({
    id: '/alumnoWebSum/v2/informacion/fichaSocioeconomica',
    path: '/alumnoWebSum/v2/informacion/fichaSocioeconomica',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlumnoWebSumV2InformacionFormularioDatosRoute =
  AlumnoWebSumV2InformacionFormularioDatosRouteImport.update({
    id: '/alumnoWebSum/v2/informacion/formularioDatos',
    path: '/alumnoWebSum/v2/informacion/formularioDatos',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlumnoWebSumV2InformacionHistorialRoute =
  AlumnoWebSumV2InformacionHistorialRouteImport.update({
    id: '/alumnoWebSum/v2/informacion/historial',
    path: '/alumnoWebSum/v2/informacion/historial',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlumnoWebSumV2InformacionPerfilRoute =
  AlumnoWebSumV2InformacionPerfilRouteImport.update({
    id: '/alumnoWebSum/v2/informacion/perfil',
    path: '/alumnoWebSum/v2/informacion/perfil',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlumnoWebSumV2MatriculaInformacionRoute =
  AlumnoWebSumV2MatriculaInformacionRouteImport.update({
    id: '/alumnoWebSum/v2/matricula/informacion',
    path: '/alumnoWebSum/v2/matricula/informacion',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlumnoWebSumV2MatriculaProgramacionRoute =
  AlumnoWebSumV2MatriculaProgramacionRouteImport.update({
    id: '/alumnoWebSum/v2/matricula/programacion',
    path: '/alumnoWebSum/v2/matricula/programacion',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlumnoWebSumV2ReportesDeudasRoute =
  AlumnoWebSumV2ReportesDeudasRouteImport.update({
    id: '/alumnoWebSum/v2/reportes/deudas',
    path: '/alumnoWebSum/v2/reportes/deudas',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlumnoWebSumV2ReportesEvaluacionesRoute =
  AlumnoWebSumV2ReportesEvaluacionesRouteImport.update({
    id: '/alumnoWebSum/v2/reportes/evaluaciones',
    path: '/alumnoWebSum/v2/reportes/evaluaciones',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlumnoWebSumV2ReportesHorariosRoute =
  AlumnoWebSumV2ReportesHorariosRouteImport.update({
    id: '/alumnoWebSum/v2/reportes/horarios',
    path: '/alumnoWebSum/v2/reportes/horarios',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlumnoWebSumV2ReportesMatriculaRoute =
  AlumnoWebSumV2ReportesMatriculaRouteImport.update({
    id: '/alumnoWebSum/v2/reportes/matricula',
    path: '/alumnoWebSum/v2/reportes/matricula',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlumnoWebSumV2ReportesPrematriculaRoute =
  AlumnoWebSumV2ReportesPrematriculaRouteImport.update({
    id: '/alumnoWebSum/v2/reportes/prematricula',
    path: '/alumnoWebSum/v2/reportes/prematricula',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alumnoWebSum/v2/asistencia': typeof AlumnoWebSumV2AsistenciaRoute
  '/alumnoWebSum/v2/inicio': typeof AlumnoWebSumV2InicioRoute
  '/alumnoWebSum/v2/manuales': typeof AlumnoWebSumV2ManualesRoute
  '/alumnoWebSum/v2/planEstudios': typeof AlumnoWebSumV2PlanEstudiosRoute
  '/alumnoWebSum/v2/tutoria': typeof AlumnoWebSumV2TutoriaRoute
  '/alumnoWebSum/v2/informacion/fichaSocioeconomica': typeof AlumnoWebSumV2InformacionFichaSocioeconomicaRoute
  '/alumnoWebSum/v2/informacion/formularioDatos': typeof AlumnoWebSumV2InformacionFormularioDatosRoute
  '/alumnoWebSum/v2/informacion/historial': typeof AlumnoWebSumV2InformacionHistorialRoute
  '/alumnoWebSum/v2/informacion/perfil': typeof AlumnoWebSumV2InformacionPerfilRoute
  '/alumnoWebSum/v2/matricula/informacion': typeof AlumnoWebSumV2MatriculaInformacionRoute
  '/alumnoWebSum/v2/matricula/programacion': typeof AlumnoWebSumV2MatriculaProgramacionRoute
  '/alumnoWebSum/v2/reportes/deudas': typeof AlumnoWebSumV2ReportesDeudasRoute
  '/alumnoWebSum/v2/reportes/evaluaciones': typeof AlumnoWebSumV2ReportesEvaluacionesRoute
  '/alumnoWebSum/v2/reportes/horarios': typeof AlumnoWebSumV2ReportesHorariosRoute
  '/alumnoWebSum/v2/reportes/matricula': typeof AlumnoWebSumV2ReportesMatriculaRoute
  '/alumnoWebSum/v2/reportes/prematricula': typeof AlumnoWebSumV2ReportesPrematriculaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alumnoWebSum/v2/asistencia': typeof AlumnoWebSumV2AsistenciaRoute
  '/alumnoWebSum/v2/inicio': typeof AlumnoWebSumV2InicioRoute
  '/alumnoWebSum/v2/manuales': typeof AlumnoWebSumV2ManualesRoute
  '/alumnoWebSum/v2/planEstudios': typeof AlumnoWebSumV2PlanEstudiosRoute
  '/alumnoWebSum/v2/tutoria': typeof AlumnoWebSumV2TutoriaRoute
  '/alumnoWebSum/v2/informacion/fichaSocioeconomica': typeof AlumnoWebSumV2InformacionFichaSocioeconomicaRoute
  '/alumnoWebSum/v2/informacion/formularioDatos': typeof AlumnoWebSumV2InformacionFormularioDatosRoute
  '/alumnoWebSum/v2/informacion/historial': typeof AlumnoWebSumV2InformacionHistorialRoute
  '/alumnoWebSum/v2/informacion/perfil': typeof AlumnoWebSumV2InformacionPerfilRoute
  '/alumnoWebSum/v2/matricula/informacion': typeof AlumnoWebSumV2MatriculaInformacionRoute
  '/alumnoWebSum/v2/matricula/programacion': typeof AlumnoWebSumV2MatriculaProgramacionRoute
  '/alumnoWebSum/v2/reportes/deudas': typeof AlumnoWebSumV2ReportesDeudasRoute
  '/alumnoWebSum/v2/reportes/evaluaciones': typeof AlumnoWebSumV2ReportesEvaluacionesRoute
  '/alumnoWebSum/v2/reportes/horarios': typeof AlumnoWebSumV2ReportesHorariosRoute
  '/alumnoWebSum/v2/reportes/matricula': typeof AlumnoWebSumV2ReportesMatriculaRoute
  '/alumnoWebSum/v2/reportes/prematricula': typeof AlumnoWebSumV2ReportesPrematriculaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alumnoWebSum/v2/asistencia': typeof AlumnoWebSumV2AsistenciaRoute
  '/alumnoWebSum/v2/inicio': typeof AlumnoWebSumV2InicioRoute
  '/alumnoWebSum/v2/manuales': typeof AlumnoWebSumV2ManualesRoute
  '/alumnoWebSum/v2/planEstudios': typeof AlumnoWebSumV2PlanEstudiosRoute
  '/alumnoWebSum/v2/tutoria': typeof AlumnoWebSumV2TutoriaRoute
  '/alumnoWebSum/v2/informacion/fichaSocioeconomica': typeof AlumnoWebSumV2InformacionFichaSocioeconomicaRoute
  '/alumnoWebSum/v2/informacion/formularioDatos': typeof AlumnoWebSumV2InformacionFormularioDatosRoute
  '/alumnoWebSum/v2/informacion/historial': typeof AlumnoWebSumV2InformacionHistorialRoute
  '/alumnoWebSum/v2/informacion/perfil': typeof AlumnoWebSumV2InformacionPerfilRoute
  '/alumnoWebSum/v2/matricula/informacion': typeof AlumnoWebSumV2MatriculaInformacionRoute
  '/alumnoWebSum/v2/matricula/programacion': typeof AlumnoWebSumV2MatriculaProgramacionRoute
  '/alumnoWebSum/v2/reportes/deudas': typeof AlumnoWebSumV2ReportesDeudasRoute
  '/alumnoWebSum/v2/reportes/evaluaciones': typeof AlumnoWebSumV2ReportesEvaluacionesRoute
  '/alumnoWebSum/v2/reportes/horarios': typeof AlumnoWebSumV2ReportesHorariosRoute
  '/alumnoWebSum/v2/reportes/matricula': typeof AlumnoWebSumV2ReportesMatriculaRoute
  '/alumnoWebSum/v2/reportes/prematricula': typeof AlumnoWebSumV2ReportesPrematriculaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alumnoWebSum/v2/asistencia'
    | '/alumnoWebSum/v2/inicio'
    | '/alumnoWebSum/v2/manuales'
    | '/alumnoWebSum/v2/planEstudios'
    | '/alumnoWebSum/v2/tutoria'
    | '/alumnoWebSum/v2/informacion/fichaSocioeconomica'
    | '/alumnoWebSum/v2/informacion/formularioDatos'
    | '/alumnoWebSum/v2/informacion/historial'
    | '/alumnoWebSum/v2/informacion/perfil'
    | '/alumnoWebSum/v2/matricula/informacion'
    | '/alumnoWebSum/v2/matricula/programacion'
    | '/alumnoWebSum/v2/reportes/deudas'
    | '/alumnoWebSum/v2/reportes/evaluaciones'
    | '/alumnoWebSum/v2/reportes/horarios'
    | '/alumnoWebSum/v2/reportes/matricula'
    | '/alumnoWebSum/v2/reportes/prematricula'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alumnoWebSum/v2/asistencia'
    | '/alumnoWebSum/v2/inicio'
    | '/alumnoWebSum/v2/manuales'
    | '/alumnoWebSum/v2/planEstudios'
    | '/alumnoWebSum/v2/tutoria'
    | '/alumnoWebSum/v2/informacion/fichaSocioeconomica'
    | '/alumnoWebSum/v2/informacion/formularioDatos'
    | '/alumnoWebSum/v2/informacion/historial'
    | '/alumnoWebSum/v2/informacion/perfil'
    | '/alumnoWebSum/v2/matricula/informacion'
    | '/alumnoWebSum/v2/matricula/programacion'
    | '/alumnoWebSum/v2/reportes/deudas'
    | '/alumnoWebSum/v2/reportes/evaluaciones'
    | '/alumnoWebSum/v2/reportes/horarios'
    | '/alumnoWebSum/v2/reportes/matricula'
    | '/alumnoWebSum/v2/reportes/prematricula'
  id:
    | '__root__'
    | '/'
    | '/alumnoWebSum/v2/asistencia'
    | '/alumnoWebSum/v2/inicio'
    | '/alumnoWebSum/v2/manuales'
    | '/alumnoWebSum/v2/planEstudios'
    | '/alumnoWebSum/v2/tutoria'
    | '/alumnoWebSum/v2/informacion/fichaSocioeconomica'
    | '/alumnoWebSum/v2/informacion/formularioDatos'
    | '/alumnoWebSum/v2/informacion/historial'
    | '/alumnoWebSum/v2/informacion/perfil'
    | '/alumnoWebSum/v2/matricula/informacion'
    | '/alumnoWebSum/v2/matricula/programacion'
    | '/alumnoWebSum/v2/reportes/deudas'
    | '/alumnoWebSum/v2/reportes/evaluaciones'
    | '/alumnoWebSum/v2/reportes/horarios'
    | '/alumnoWebSum/v2/reportes/matricula'
    | '/alumnoWebSum/v2/reportes/prematricula'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlumnoWebSumV2AsistenciaRoute: typeof AlumnoWebSumV2AsistenciaRoute
  AlumnoWebSumV2InicioRoute: typeof AlumnoWebSumV2InicioRoute
  AlumnoWebSumV2ManualesRoute: typeof AlumnoWebSumV2ManualesRoute
  AlumnoWebSumV2PlanEstudiosRoute: typeof AlumnoWebSumV2PlanEstudiosRoute
  AlumnoWebSumV2TutoriaRoute: typeof AlumnoWebSumV2TutoriaRoute
  AlumnoWebSumV2InformacionFichaSocioeconomicaRoute: typeof AlumnoWebSumV2InformacionFichaSocioeconomicaRoute
  AlumnoWebSumV2InformacionFormularioDatosRoute: typeof AlumnoWebSumV2InformacionFormularioDatosRoute
  AlumnoWebSumV2InformacionHistorialRoute: typeof AlumnoWebSumV2InformacionHistorialRoute
  AlumnoWebSumV2InformacionPerfilRoute: typeof AlumnoWebSumV2InformacionPerfilRoute
  AlumnoWebSumV2MatriculaInformacionRoute: typeof AlumnoWebSumV2MatriculaInformacionRoute
  AlumnoWebSumV2MatriculaProgramacionRoute: typeof AlumnoWebSumV2MatriculaProgramacionRoute
  AlumnoWebSumV2ReportesDeudasRoute: typeof AlumnoWebSumV2ReportesDeudasRoute
  AlumnoWebSumV2ReportesEvaluacionesRoute: typeof AlumnoWebSumV2ReportesEvaluacionesRoute
  AlumnoWebSumV2ReportesHorariosRoute: typeof AlumnoWebSumV2ReportesHorariosRoute
  AlumnoWebSumV2ReportesMatriculaRoute: typeof AlumnoWebSumV2ReportesMatriculaRoute
  AlumnoWebSumV2ReportesPrematriculaRoute: typeof AlumnoWebSumV2ReportesPrematriculaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumnoWebSum/v2/asistencia': {
      id: '/alumnoWebSum/v2/asistencia'
      path: '/alumnoWebSum/v2/asistencia'
      fullPath: '/alumnoWebSum/v2/asistencia'
      preLoaderRoute: typeof AlumnoWebSumV2AsistenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumnoWebSum/v2/inicio': {
      id: '/alumnoWebSum/v2/inicio'
      path: '/alumnoWebSum/v2/inicio'
      fullPath: '/alumnoWebSum/v2/inicio'
      preLoaderRoute: typeof AlumnoWebSumV2InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumnoWebSum/v2/manuales': {
      id: '/alumnoWebSum/v2/manuales'
      path: '/alumnoWebSum/v2/manuales'
      fullPath: '/alumnoWebSum/v2/manuales'
      preLoaderRoute: typeof AlumnoWebSumV2ManualesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumnoWebSum/v2/planEstudios': {
      id: '/alumnoWebSum/v2/planEstudios'
      path: '/alumnoWebSum/v2/planEstudios'
      fullPath: '/alumnoWebSum/v2/planEstudios'
      preLoaderRoute: typeof AlumnoWebSumV2PlanEstudiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumnoWebSum/v2/tutoria': {
      id: '/alumnoWebSum/v2/tutoria'
      path: '/alumnoWebSum/v2/tutoria'
      fullPath: '/alumnoWebSum/v2/tutoria'
      preLoaderRoute: typeof AlumnoWebSumV2TutoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumnoWebSum/v2/informacion/fichaSocioeconomica': {
      id: '/alumnoWebSum/v2/informacion/fichaSocioeconomica'
      path: '/alumnoWebSum/v2/informacion/fichaSocioeconomica'
      fullPath: '/alumnoWebSum/v2/informacion/fichaSocioeconomica'
      preLoaderRoute: typeof AlumnoWebSumV2InformacionFichaSocioeconomicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumnoWebSum/v2/informacion/formularioDatos': {
      id: '/alumnoWebSum/v2/informacion/formularioDatos'
      path: '/alumnoWebSum/v2/informacion/formularioDatos'
      fullPath: '/alumnoWebSum/v2/informacion/formularioDatos'
      preLoaderRoute: typeof AlumnoWebSumV2InformacionFormularioDatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumnoWebSum/v2/informacion/historial': {
      id: '/alumnoWebSum/v2/informacion/historial'
      path: '/alumnoWebSum/v2/informacion/historial'
      fullPath: '/alumnoWebSum/v2/informacion/historial'
      preLoaderRoute: typeof AlumnoWebSumV2InformacionHistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumnoWebSum/v2/informacion/perfil': {
      id: '/alumnoWebSum/v2/informacion/perfil'
      path: '/alumnoWebSum/v2/informacion/perfil'
      fullPath: '/alumnoWebSum/v2/informacion/perfil'
      preLoaderRoute: typeof AlumnoWebSumV2InformacionPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumnoWebSum/v2/matricula/informacion': {
      id: '/alumnoWebSum/v2/matricula/informacion'
      path: '/alumnoWebSum/v2/matricula/informacion'
      fullPath: '/alumnoWebSum/v2/matricula/informacion'
      preLoaderRoute: typeof AlumnoWebSumV2MatriculaInformacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumnoWebSum/v2/matricula/programacion': {
      id: '/alumnoWebSum/v2/matricula/programacion'
      path: '/alumnoWebSum/v2/matricula/programacion'
      fullPath: '/alumnoWebSum/v2/matricula/programacion'
      preLoaderRoute: typeof AlumnoWebSumV2MatriculaProgramacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumnoWebSum/v2/reportes/deudas': {
      id: '/alumnoWebSum/v2/reportes/deudas'
      path: '/alumnoWebSum/v2/reportes/deudas'
      fullPath: '/alumnoWebSum/v2/reportes/deudas'
      preLoaderRoute: typeof AlumnoWebSumV2ReportesDeudasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumnoWebSum/v2/reportes/evaluaciones': {
      id: '/alumnoWebSum/v2/reportes/evaluaciones'
      path: '/alumnoWebSum/v2/reportes/evaluaciones'
      fullPath: '/alumnoWebSum/v2/reportes/evaluaciones'
      preLoaderRoute: typeof AlumnoWebSumV2ReportesEvaluacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumnoWebSum/v2/reportes/horarios': {
      id: '/alumnoWebSum/v2/reportes/horarios'
      path: '/alumnoWebSum/v2/reportes/horarios'
      fullPath: '/alumnoWebSum/v2/reportes/horarios'
      preLoaderRoute: typeof AlumnoWebSumV2ReportesHorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumnoWebSum/v2/reportes/matricula': {
      id: '/alumnoWebSum/v2/reportes/matricula'
      path: '/alumnoWebSum/v2/reportes/matricula'
      fullPath: '/alumnoWebSum/v2/reportes/matricula'
      preLoaderRoute: typeof AlumnoWebSumV2ReportesMatriculaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumnoWebSum/v2/reportes/prematricula': {
      id: '/alumnoWebSum/v2/reportes/prematricula'
      path: '/alumnoWebSum/v2/reportes/prematricula'
      fullPath: '/alumnoWebSum/v2/reportes/prematricula'
      preLoaderRoute: typeof AlumnoWebSumV2ReportesPrematriculaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlumnoWebSumV2AsistenciaRoute: AlumnoWebSumV2AsistenciaRoute,
  AlumnoWebSumV2InicioRoute: AlumnoWebSumV2InicioRoute,
  AlumnoWebSumV2ManualesRoute: AlumnoWebSumV2ManualesRoute,
  AlumnoWebSumV2PlanEstudiosRoute: AlumnoWebSumV2PlanEstudiosRoute,
  AlumnoWebSumV2TutoriaRoute: AlumnoWebSumV2TutoriaRoute,
  AlumnoWebSumV2InformacionFichaSocioeconomicaRoute:
    AlumnoWebSumV2InformacionFichaSocioeconomicaRoute,
  AlumnoWebSumV2InformacionFormularioDatosRoute:
    AlumnoWebSumV2InformacionFormularioDatosRoute,
  AlumnoWebSumV2InformacionHistorialRoute:
    AlumnoWebSumV2InformacionHistorialRoute,
  AlumnoWebSumV2InformacionPerfilRoute: AlumnoWebSumV2InformacionPerfilRoute,
  AlumnoWebSumV2MatriculaInformacionRoute:
    AlumnoWebSumV2MatriculaInformacionRoute,
  AlumnoWebSumV2MatriculaProgramacionRoute:
    AlumnoWebSumV2MatriculaProgramacionRoute,
  AlumnoWebSumV2ReportesDeudasRoute: AlumnoWebSumV2ReportesDeudasRoute,
  AlumnoWebSumV2ReportesEvaluacionesRoute:
    AlumnoWebSumV2ReportesEvaluacionesRoute,
  AlumnoWebSumV2ReportesHorariosRoute: AlumnoWebSumV2ReportesHorariosRoute,
  AlumnoWebSumV2ReportesMatriculaRoute: AlumnoWebSumV2ReportesMatriculaRoute,
  AlumnoWebSumV2ReportesPrematriculaRoute:
    AlumnoWebSumV2ReportesPrematriculaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
